spring:
  application:
    name: forum
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/forumdb
    username: admin
    password: admin

    hikari:
      schema: forum

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
    show-sql: true


  flyway:
    enabled: true
    validate-on-migrate: true
    schemas: forum

server:
  port: 9001


