spring:
  application:
    name: forum
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_HOST_PORT}/${DB_NAME}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD}

    hikari:
      schema: forum

  jpa:
    #properties:
      #hibernate:
        #format_sql: true
    hibernate:
      ddl-auto: update
    #show-sql: true

  flyway:
    enabled: true
    validate-on-migrate: true
    schemas: forum

client:
  host: ${CLIENT_HOST:3000}


