spring:
  application:
    name: forum
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_HOST_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

    hikari:
      schema: forumdb

  jpa:
    #properties:
      #hibernate:
        #format_sql: true
    hibernate:
      ddl-auto: update
    #show-sql: true

  flyway:
    enabled: true
    validate-on-migrate: true
    schemas: forumdb

client:
  host: ${CLIENT_HOST:3000}


