services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: forumdb
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pgnet

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    env_file:
      - testing.env
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - pgnet

  app:
    tty: true
#    build:
#      context: .
#      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - testing.env
    networks:
      - pgnet

# ENABLE FOR DEVELOPING IN A CONTAINER
    image: maven:3.9.9-eclipse-temurin-21-jammy
    volumes:
      - ./src:/home/app/src
      - ./target:/home/app/target
      - ./pom.xml:/home/app/pom.xml
    command: tail -f /dev/null # Keep the container running

volumes:
  pgdata:
    driver: local

networks:
  pgnet:
