spring:
  application:
    name: forum
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_ADDRESS}:5432/forumdb
    username: ${POSTGRES_ADMIN_USERNAME}
    password: ${POSTGRES_ADMIN_PASSWORD}

    hikari:
      schema: forum

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    validate-on-migrate: true
    schemas: forum

server:
  port: 9001


