spring:
  application:
    name: forum
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/forumdb
    username: admin
    password: admin

    hikari:
      schema: forum

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    validate-on-migrate: true
    schemas: forum

server:
  port: 9001


