-- Simplified schema reset and consolidation
-- This migration consolidates all previous migrations into a clean state

-- Drop existing tables to start fresh (if they exist)
DROP TABLE IF EXISTS forum.votes CASCADE;
DROP TABLE IF EXISTS forum.reply_entity CASCADE;
DROP TABLE IF EXISTS forum.topic_entity CASCADE;

-- Create topic table with proper structure
CREATE TABLE forum.topic_entity (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(255) NOT NULL UNIQUE,
    created_on TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    modified_on TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
);

-- Create reply table with proper structure
CREATE TABLE forum.reply_entity (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    content TEXT NOT NULL,
    topic_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_on TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    modified_on TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_reply_topic FOREIGN KEY (topic_id) REFERENCES forum.topic_entity(id) ON DELETE CASCADE
);

-- Create votes table with simplified structure (without entity_type column)
CREATE TABLE forum.votes (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    vote_type VARCHAR(10) NOT NULL CHECK (vote_type IN ('UPVOTE', 'DOWNVOTE')),
    topic_or_reply_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_on TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    modified_on TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_user_vote UNIQUE(user_id, topic_or_reply_id)
);

-- Create indexes for optimal performance
CREATE INDEX idx_reply_topic_id ON forum.reply_entity (topic_id);
CREATE INDEX idx_reply_user_id ON forum.reply_entity (user_id);
CREATE INDEX idx_votes_topic_or_reply_id ON forum.votes (topic_or_reply_id);
CREATE INDEX idx_votes_user_id ON forum.votes (user_id);
CREATE INDEX idx_topic_created_on ON forum.topic_entity (created_on DESC);

-- Insert sample topics
INSERT INTO forum.topic_entity (title, created_on, modified_on) VALUES
('Welcome to the Forum!', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('How to ask a good question?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Forum Rules and Guidelines', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Introduce Yourself', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Technical Support', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('General Discussion', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Programming Tips', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Best Practices', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Off-Topic', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Feature Requests', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Insert sample replies
INSERT INTO forum.reply_entity (content, topic_id, user_id, created_on, modified_on) VALUES
-- Replies for "Welcome to the Forum!" (topic_id: 1)
('Thank you for the warm welcome! I''m excited to be part of this community.', 1, 101, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Great to see such an active forum. Looking forward to contributing!', 1, 102, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Hello everyone! This seems like a fantastic place to learn and share knowledge.', 1, 103, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Replies for "How to ask a good question?" (topic_id: 2)
('Always include what you''ve tried so far and what specific error you''re getting.', 2, 104, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Make sure to provide a minimal reproducible example. It helps others understand your issue quickly.', 2, 105, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Don''t forget to search for existing similar questions before posting!', 2, 106, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Clear titles are crucial - they help others find your question when they have similar issues.', 2, 107, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Replies for "Forum Rules and Guidelines" (topic_id: 3)
('These rules make sense. Respect and constructive communication should be the foundation.', 3, 108, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Thanks for laying out clear expectations. This will help maintain a positive environment.', 3, 109, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Replies for "Introduce Yourself" (topic_id: 4)
('Hi! I''m a software developer with 5 years of experience in Java and Spring Boot.', 4, 110, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Hello! I''m new to programming and currently learning web development.', 4, 111, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Greetings! I''m a data scientist interested in machine learning and AI.', 4, 112, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Hey everyone! I''m a student studying computer science, excited to learn from you all.', 4, 113, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Replies for "Technical Support" (topic_id: 5)
('I''m having trouble with my database connection. The error says "Connection refused".', 5, 114, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Check if your database service is running and if the port is correct.', 5, 115, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Also verify your connection string and credentials.', 5, 116, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Replies for "Programming Tips" (topic_id: 7)
('Always write unit tests for your critical business logic!', 7, 117, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Use meaningful variable names - your future self will thank you.', 7, 118, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Don''t repeat yourself (DRY principle) - extract common functionality into reusable methods.', 7, 119, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Comment your code, but make sure the comments explain WHY, not WHAT.', 7, 120, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Replies for "Best Practices" (topic_id: 8)
('Code reviews are essential - they catch bugs and help spread knowledge across the team.', 8, 121, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Version control is your friend - commit often with descriptive messages.', 8, 122, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Keep your dependencies up to date, but test thoroughly after updates.', 8, 123, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Replies for "Feature Requests" (topic_id: 10)
('It would be great to have a dark mode for the forum!', 10, 124, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Can we add a search functionality to find topics and replies quickly?', 10, 125, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Email notifications for replies would be very useful.', 10, 126, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
